include(CheckFunctionExists)
macro(set_function_macro func name)
    check_function_exists(${func} ${name})
    if(${name})
        add_definitions(-D${name})
    endif(${name})
endmacro()
set_function_macro(printf HAVE_PRINTF)
set_function_macro(prctl HAVE_PRCTL)
set_function_macro(kqueue HAVE_KQUEUE)
set_function_macro(epoll HAVE_EPOLL)
set_function_macro(poll HAVE_POLL)
set_function_macro(select HAVE_SELECT)
